### ISSUE TITLE
Bug: The $in operator doesn't work with createQueryTester

### ISSUE THREAD

**Issue by J3m5** [crcn/sift.js#240]
If you look at the sandbox reproduction case, the $in operator has no effect when used with the createQueryTester function, even with all the other operators added:
https://codesandbox.io/s/sift-in-bug-zezf1?file=/src/index.js

Am I missing something ?

**Comment by J3m5** [comment]
After doing more tests, i looks like that is concerns more operators like the $eq and $gt.

**Comment by J3m5** [comment]
I tried to run the tests but I get the following error: `Error: Cannot find module '../src'`
I'm using node 16.3.1 by the way.

**Comment by crcn** [comment]
Looks like you have a syntax error in that example, it should be `createQueryTester(query, { operations: { $in, ... }})`. Here's the test for that: https://github.com/crcn/sift.js/blob/master/test/operations-test.js#L772.

**Comment by J3m5** [comment]
Ah, ok, I see now.
I've used the docs in the readme as an example:
https://github.com/crcn/sift.js#omitting-built-in-operations

```js
import { createQueryTester, $in, $all, $nin, $lt } from "sift";
const test = createQueryTester(
  {
    $eq: 10
  },
  { $in, $all, $nin, $lt }
);

[1, 2, 3, 4, 10].filter(test);
```

No operators there

Do you have any idea about why I get this error when I run the tests?

**Comment by crcn** [comment]
oh! Thanks for catching that, the README should be fixed now.

> Do you have any idea about why I get this error when I run the tests?

You need to build the library before you can run tests

**Comment by J3m5** [comment]
That's what I did, and I can recall running the tests some time ago...

**Comment by crcn** [comment]
That's strange, what command are you using to build the library?

**Comment by J3m5** [comment]
I've tried the build script only, build:types only, and both.
I tried with npm and yarn, still the same

```
sift.js on  master [!] is 📦 v15.0.0 via  v16.13.1 took 11s 
❯ npm run test

> sift@15.0.0 test
> npm run test:spec && npm run test:types


> sift@15.0.0 test:spec
> mocha ./test -R spec


Error: Cannot find module '../src'
Require stack:
- /home/jeremy/dev/perso/sift.js/test/async-test.js
- /home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/esm-utils.js
- /home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/mocha.js
- /home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/cli/one-and-dones.js
- /home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/cli/options.js
- /home/jeremy/dev/perso/sift.js/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jeremy/dev/perso/sift.js/test/async-test.js:2:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (/home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/home/jeremy/dev/perso/sift.js/node_modules/mocha/lib/cli/run.js:362:11)
    at /home/jeremy/dev/perso/sift.js/node_modules/yargs/build/index.cjs:443:71
    ```

**Comment by J3m5** [comment]
No, I'm seeing this:
```
❯ npm run clean && npm run build:types

> sift@15.0.0 clean
> rimraf lib es5m es


> sift@15.0.0 build:types
> tsc -p tsconfig.json --emitDeclarationOnly --outDir lib
```
Nothing more, and no files are generated in the src folder

**Comment by crcn** [comment]
What about `npm run build`?

**Comment by J3m5** [comment]
```
❯ npm run build

> sift@15.0.0 prebuild
> npm run clean && npm run build:types


> sift@15.0.0 clean
> rimraf lib es5m es


> sift@15.0.0 build:types
> tsc -p tsconfig.json --emitDeclarationOnly --outDir lib


> sift@15.0.0 build
> rollup -c


src/index.ts → es...
created es in 1.2s

src/index.ts → es5m...
created es5m in 690ms

src/index.ts → lib...
created lib in 683ms

src/index.ts → sift.min.js...
created sift.min.js in 1.3s

src/index.ts → sift.csp.min.js...
created sift.csp.min.js in 568ms
```

**Comment by crcn** [comment]
That should do the trick, what happens when you run `npm test` now?

**Comment by crcn** [comment]
Fixed! Let me know if this issue is still there.

**Comment by J3m5** [comment]
I had to change `custom-operations-test.js`, `object-test.js` and `types.js` import from `../src` to `../lib` like the others to make it works, but yes it's working, thanks!
